### ISSUE TITLE
Docs Links not working - ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by monpie3** [mieweb/docs#31]
**Describe the bug**

**To Reproduce**
1. Go to https://docs.enterprisehealth.com/
2. Search something.
![image](https://github.com/user-attachments/assets/60d30540-19c0-4723-9ec3-eacb127fd2ea)

4. Error after clicking link from Search:
![image](https://github.com/user-attachments/assets/5078b0c2-2e50-41d4-8537-33001ad34dae)

This is occurring for both EH and Webchart Docs

**Additional context from Will**
I don't think that webchart is using the correct URL when searching. 

Searching URLs should be https://docs.enterprisehealth.com/en/#search=patient NOT https://docs.enterprisehealth.com/index#search=patient

I'm not sure when the "/en/" was added to the URL. Maybe this is a new thing on wikigdrive for multi-lingual?

**Comment by ggodlewski** [comment]
@wreiske Can you check https://github.com/mieweb/docs/actions/runs/10203345954/job/28229588533 ?
It says no route to host while deploying.
