### ISSUE TITLE
CI / build Queued but Never Completes

### ISSUE THREAD

**Issue by jennananderson** [mieweb/docs#33]
The CI / build shows as queued but never seems to complete. Some documents were committed two days ago and still show pending. This appears to be holding up publishing as well. 

Here is a screenshot of the message when I tried publishing:
![image](https://github.com/user-attachments/assets/c4c9a6fc-0a89-4c52-8f79-20c47fa43688)

**Comment by monpie3** [comment]
I asked Dave if we didn't restart something after a zeus reboot.

**Comment by monpie3** [comment]
It should be working now, to be closed after @jennananderson tests
