### ISSUE TITLE
wikigdrive and docs repo are out of sync

### ISSUE THREAD

**Issue by monpie3** [mieweb/docs#36]
Doug's latest commit isn't showing up in the git log on wikigdrive.
Alice's new commits aren't reaching GitHub.

![image](https://github.com/user-attachments/assets/0f2085ba-d186-41ca-bed4-9547af9d2a4d)

![image](https://github.com/user-attachments/assets/5216370c-4d2b-43c0-afa9-64a99425a675)

**Comment by wreiske** [comment]
Usually when this happens, I go into the "danger zone" and reset git to the remote.

![image](https://github.com/user-attachments/assets/fb74f737-c5ae-4817-9c80-d919a30254ac)

I just did this and it's transforming the markdown now. Let me know if you're still having issues.

**Comment by ggodlewski** [comment]
Did you try git pull?

**Comment by monpie3** [comment]
I couldn't because there were changes that weren't stash. We could think about adding git stash button maybe or wrapping `git pull` with `git stash`. 

I close the ticket since it's working again properly.
