### ISSUE TITLE
New folders are missing 

### ISSUE THREAD

**Issue by monpie3** [mieweb/docs#37]
Alice added a new subfolder for "Artificial Intelligence" under the "Functions" folder. She gave it a landing page. Then also added document within that folder.

I can find Artificial Intelligence page:
https://docs.enterprisehealth.com/functions/artificial-intelligence/ai-chat-box/#search=artificial
but it downloads instead of displaying when I click on it.

I can find also AI Chat Box page:
https://docs.enterprisehealth.com/functions/artificial-intelligence/ai-chat-box/
But when I try to access `artificial-intelligence` I get `403 Forbidden`

![image](https://github.com/user-attachments/assets/23d61b8e-1716-4655-8f2e-20940e183985)

![image](https://github.com/user-attachments/assets/4813bd72-d6f4-4dc4-a8f9-2f5aa483c0e4)

![image](https://github.com/user-attachments/assets/cf5e371d-8fb9-4ade-a802-f9abaef170bd)

There is a difference between what is displayed in the preview and what is on the prod (despite making release):
In preview the new tab exists in correct place: https://wikigdrive.com/preview/0AF_nrE0_QH_2Uk9PVA/_manual/
![image](https://github.com/user-attachments/assets/05918d3a-46eb-4899-afb7-72a1759fca69)

But in prod system it's here: [Enterprise Health :: Documentation Home](https://docs.enterprisehealth.com/)
![image](https://github.com/user-attachments/assets/b5f0e465-74cc-49fa-b6f6-e36a8426784e)

**Comment by ggodlewski** [comment]
File artificial-intelligence.md is not committed

![image](https://github.com/user-attachments/assets/de362a4e-3598-4720-99e7-e6acd8dd5ef8)

https://wikigdrive.com/drive/0AF_nrE0_QH_2Uk9PVA/content/functions/artificial-intelligence.md#git_commit

There is only redirection https://github.com/mieweb/docs/blob/master/content/functions/artifical-intelligence.md commited.

**Comment by auhrick** [comment]
I don't know what I am supposed to do. I published the document and i see it on the online help, but it downloads instead of directing me to the document. I'm sure I am doing something wrong. This is the first I have added a folder.

![image](https://github.com/user-attachments/assets/84399160-4171-4a31-aac1-2e6bfba5b03a)

**Comment by monpie3** [comment]
It is now working correctly – closing the issue.
