### ISSUE TITLE
Missing Subfolders under "Functions"

### ISSUE THREAD

**Issue by auhrick** [mieweb/docs#38]
I've updated documentation on a few documents, but the folder that contains this fuctionality isn't on the nav page. 

Can we add these back to the nav page?

![image](https://github.com/user-attachments/assets/b499620f-6ff1-4ba0-9957-93f508c4e6a6)
![image](https://github.com/user-attachments/assets/b7beb030-d1a6-4c24-8007-c3b4523d18fa)

**Comment by ggodlewski** [comment]
File doc added for the index
![image](https://github.com/user-attachments/assets/31fd39ca-40ef-44e8-92d4-e8ba91e7da15)

**Comment by monpie3** [comment]
It is now working correctly – closing the issue.
