### ISSUE TITLE
Unable to search for "Financials Pending Billing" document

### ISSUE THREAD

**Issue by auhrick** [mieweb/docs#40]
The "Financials Pending Billing" documentation was published, but I can not search for it on the client facing online help. I see another report called "Financials Pending Encounters", but not "Financials Pending Billing"
![image](https://github.com/user-attachments/assets/9ff9d892-2f94-49c0-aa27-1c5a844dbd69)

I can however find the document in the navigation pane, and I can click on it to get to the document.
![image](https://github.com/user-attachments/assets/daf2e570-c266-4d76-94db-1f5f11084858)

Same with searching for "Financials All Active Deals-Detail Report".  I can not find the document when searching using the online help, but  I can get to it using the navigation pane.
![image](https://github.com/user-attachments/assets/fc299a6a-69ba-47ff-b131-7f88220afa8a)

And with "Copy from Previous Exam"
![image](https://github.com/user-attachments/assets/276cf206-2a85-4d0b-b397-2a0d1a8a36da)

Why can't I find for it when searching for the document?

**Comment by ggodlewski** [comment]
I'm able to find both files:

![image](https://github.com/user-attachments/assets/0a654dd6-be69-4cd7-a227-dead973545cb)

Maybe try refreshing website?

**Comment by auhrick** [comment]
I am able to find them today. I'm not sure why they were not searchable last week.
