### ISSUE TITLE
Document name change issue

### ISSUE THREAD

**Issue by auhrick** [mieweb/docs#52]
Issue:

I created a document and called it "Assigned Encounters". Published it. it was all fine. Then I realized the feature is called "Assigned Users", so I renamed my document, updated the language on the Nav and republished both the nav and my document.

Assigned Users Google Document:https://docs.google.com/document/d/1R93vjLpsr5E2ca9p6vbRU-8C2i-lcK62KAWizcMQQ4c/edit?tab=t.0
Commit to see name change: https://github.com/mieweb/docs/commit/f2b77bbbe812baf4afd6bf2dbdc0e77b65526208

Now, I can't find the document by either name when I search https://docs.enterprisehealth.com/

I did actually save a link in my notes after publishing it the first time: https://docs.enterprisehealth.com/functions/encounters/assigned-encounters/   
As you can see the document name did not update on this link, it still shows the old name. It also shows as last published as 10/31 and I republished it today 11/1
![image](https://github.com/user-attachments/assets/2b275c9c-497e-4269-80d9-9e3823199dd6)

Sorry, Doug warned us not to change the document name b/c its a PIA to fix. But it shouldn't be his hard. :(

**Comment by monpie3** [comment]
Solution: File was committed directly from wikigdrive: https://github.com/mieweb/docs/commit/b0cef2335012e513fef8f37ca19337f2d2797b64

Fixed now.
