### ISSUE TITLE
Add Restrictions guide won't publish (don't get the Push & Commit button or free text area)

### ISSUE THREAD

**Issue by anichols27** [mieweb/docs#64]
Hi Monika, I made updates to Add Restrictions guide: https://docs.google.com/document/d/1iIBBj7YhPN--toi1eztojxqRu70YpPCulg8vowFjRlg/edit?tab=t.0
And I don't get the normal 'commit & push' free text field to type in nor push. I just get the above and can't get my updates published. Do you know why this document is different behavior or how to get it published with the modifications?

![clip](https://github.com/user-attachments/assets/ebac32ca-cefa-466b-ba9d-5d6364cd645b)

**Comment by monpie3** [comment]
I checked logs (https://wikigdrive.com/drive/0AF_nrE0_QH_2Uk9PVA#drive_logs:job-c90b0f27-6763-47ef-8e18-58455b311a2b), and file `adding-restrictions.md` shows as transformed there.  

![image](https://github.com/user-attachments/assets/e74f5267-bcdc-4ad9-8ed9-83e200abd6be)


Not sure why it isn't in the plugin. Could you please take a look at his @ggodlewski ?

**Comment by monpie3** [comment]
Maybe it's related? I noticed the problem with displaying the commit options directly in wikigdrive:    https://github.com/mieweb/wikiGDrive/issues/526

**Comment by ggodlewski** [comment]
@monpie3 this issue does not exist on https://pr-514.wikigdrive.com/gdocs/0AF_nrE0_QH_2Uk9PVA/1iIBBj7YhPN--toi1eztojxqRu70YpPCulg8vowFjRlg
We need to do the release.

**Comment by monpie3** [comment]
The issue should be resolved, please reopen if it occurs again @anichols27
